version: '3.7'

services:
  server:
    build: ./emotion-recognition-using-speech
    command: uvicorn main:app --reload
    ports:
      - 8000:8000
    depends_on:
      - db
  client:
    build: ./client
    command: npm start
    ports:
      - 3000:3000
    depends_on:
      - server

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=thien
      - POSTGRES_DB=emotion
    expose: 
      - 5433

volumes:
  postgres_data: